[package]
name = "wwizard"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
nom = "7.1.3"
ratatui = "0.29.0"
tui-textarea = "0.7.0"
pyo3 = { git = "https://github.com/pyo3/pyo3", features = ["extension-module"] }
